### ISSUE TITLE
README: change `cf env web` to something service-specific

### ISSUE THREAD

**Issue by fureigh** [cloud-gov/cf-ex-drupal8#11]
## Current state
The README tells our gentle readers to run `cf env web` to get the credentials for their S3 bucket. This works, but only if the reader has already pushed the app once, and it requires a bit of weeding through the non-S3 env data.

## Desired state
Change the `cf env web` line to be specifically about the relevant S3 service, currently called `storage`.

**Comment by pburkholder** [comment]
https://github.com/18F/cf-ex-drupal8/pulls solves this, sort of, by replacing actual AWS S3 with a local Minio S3 emulation in Docker. Should that be merged in and obviate this need?

**Comment by fureigh** [comment]
Absolutely. Finally taking a closer look at it now — thank you!

**Comment by fureigh** [comment]
(https://github.com/18F/cf-ex-drupal8/pull/7, that is)
