### ISSUE TITLE
Document options for locking down a production instance

### ISSUE THREAD

**Issue by fureigh** [cloud-gov/cf-ex-drupal8#15]
[stub] ex: Restricting logins to certain IP addresses, config_split, etc.

**Comment by LindsayYoung** [comment]
I think adding config split here might be helpful. I can morph this issue to do that or create a new issue.

**Comment by fureigh** [comment]
@LindsayYoung Please create a new issue, referencing it from this one as a subissue if you'd like. 👍 That way we don't lose track of the non-`config_split` TODOs. (Which I can make less stubby.) Thanks!

**Comment by LindsayYoung** [comment]
Ok created the issue and it's inprogress https://github.com/18F/cf-ex-drupal8/issues/18
