### ISSUE TITLE
Update USWDS and sample subtheme to 2.x

### ISSUE THREAD

**Issue by fureigh** [cloud-gov/cf-ex-drupal8#20]
## User story
As a developer using this repo as a starting point, I want the sample USWDS theme to be the most recent major version so that I can benefit from the new version’s improvements and avoid having to unnecessarily rearchitect my theme later. 
  
## Acceptance criteria
- [ ] USDWS theme is updated to latest 2.x-based version
- [ ] Dependencies have been updated accordingly
- [ ] Sample subtheme incorporates any changes
- [ ] Site looks reasonable :)

## Technical notes
Check the status of the uswds_ paragraphs module too; if it hasn’t been updated to include 2.x, that’s a possible blocker.

**Comment by mheadd** [comment]
Issue addressed by [this](https://github.com/cloud-gov/cf-ex-drupal8/pull/48) PR merge.
