### ISSUE TITLE
bin/composer install does not execute

### ISSUE THREAD

**Issue by spitt16** [cloud-gov/cf-ex-drupal8#22]
I am following the steps of cf-ex-drupal8, but every time I get to the 
bin/composer install step, I receive the message below.

C:\Users\sonyango>cd cf-ex-drupal8

C:\Users\sonyango\cf-ex-drupal8>bin/composer install
'bin' is not recognized as an internal or external command,
operable program or batch file.

**Comment by cwilkescw** [comment]
I get that on Docker for Windows. I have been able to cd into the bin directory and then run "composer install". Docker for Windows then finds the composer.json is the main directory and it runs.

![image](https://user-images.githubusercontent.com/5607148/59616052-ae760900-90f1-11e9-80d0-ab9e3749d55d.png)
