### ISSUE TITLE
Works on Windows

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/cf-ex-drupal8#34]
## User story
As a Windows OS user, I want Powershell versions of key scripts so that I can deploy and iterate on Drupal with tools that are familiar (and likely to be approved by my organization). 
  
## Acceptance criteria
- [ ] Installs onto cloud.gov with Powershell instead of Bash
- [ ] Works with Windows docker for local dev (high bar given lack of access to Windows docker)

## Definition of done
- [ ] Guidance tested by 3rd party Windows user
- [ ] Appveyor tests (high bar)

**Comment by mogul** [comment]
Powershell Core works on Mac, Linux, etc and [can be installed using `homebrew`](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-6).

**Comment by mogul** [comment]
The only scripts that we're talking about here are `deploy-cloudgov.sh` and `delete-cloudgov.sh`, right? (I believe everything else runs in a Docker container or on a Linux host inside cloud.gov.)

**Comment by pburkholder** [comment]
I think something like `bin/composer install` may not work as expected on Windows.
