### ISSUE TITLE
Updating Dependencies Breaks Install

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/cf-ex-drupal8#49]
Given the current state of this repo, there are a number of dependencies that are out of date, as well as Drupal Core.

Running the following command successfully updated Drupal core to 8.9.0:

```
./bin/composer require drupal/core:8.9.0 drupal/pathauto:1.8.0 egulias/email-validator:2.0.0 typo3/phar-stream-wrapper:3.1.3
```

However, when attempting to run `docker-compose up` after making this change, the bootstrap script throws an error.

```
web_1       |  [ERROR] Command "config:import", is not a valid command name. 
```

[This is the line in the bootstrap script](https://github.com/cloud-gov/cf-ex-drupal8/blob/master/bootstrap.sh#L60) that causes the error. Not sure why this occurs, as it appears to be related to Drupal console, which is not changed by the update command listed above.

**Comment by mheadd** [comment]
I think I understand more fully what is happening here. When the Drupal core version is upgraded to 8.9+, the `bootstrap.sh` fails at the config import step. It's confusing because the error suggests that the command is invalid, but [this behavior has been observed with Drupal Console before ](https://github.com/hechoendrupal/drupal-console/issues/2962#issuecomment-266814231)when there is an error that causes an exception to occur. 

Something about the [contents or structure of the config](https://github.com/cloud-gov/cf-ex-drupal8/tree/master/web) that is initially imported is causing Drupal Console to choke at this step

**Comment by mheadd** [comment]
This relates to the work for #50

**Comment by onelittlebecca** [comment]
Needs to be updated and config strategy needs to be implemented -- most likely using config split or something of that nature; this will be advantageous for us regardless as it allows for different config settings for different environments. Big fan!
