### ISSUE TITLE
Fix issues with running locally on Docker

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/cf-ex-drupal8#65]
In order to provide a valuable reference for Drupal 8 installations, we want to make sure that this repo can be used to provision a Drupal 8 instance locally using Docker

Currently trying to run a Drupal 8 site using Docker is failing with:

> cf-ex-drupal8-web-1       |  [ERROR] Command "config:import", is not a valid command name.

## Acceptance Criteria
* [ ] WHEN someone follows the README instructions to run a Drupal 8 website using Docker \
  THEN they can access and use that Drupal 8 website successfully

--- 

## Security considerations

None

## Implementation sketch

* [ ] Try to run Drupal 8 via Docker and debug/fix issues

## Related

- https://github.com/cloud-gov/cf-ex-drupal8/issues/49

**Comment by mogul** [comment]
@markdboyd I put this on the board in `Doing` but if you're not actually going to continue the work, we can drop it at the bottom of the backlog.

**Comment by markdboyd** [comment]
@mogul I plan to keep working on this today
